version: '3.3'

services:
  web:
    build: .
    volumes:
        - '.:/var/www/app:delegated'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/var/www/app/
    ports:
      - 8000:8000
    stop_signal: SIGINT
    environment:
      PYTHONUNBUFFERED: 0
