version: '3.3'

services:
  web:
    build: .
    command: python3.8 manage.py runserver 0.0.0.0:8989
    volumes:
        - '.:/var/www/app:delegated'
    volumes:
      - .:/var/www/app/
    ports:
      - 8989:8989
    env_file:
      - ./.env.dev
    stop_signal: SIGINT
    environment:
      PYTHONUNBUFFERED: 0
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=polls_django
      - POSTGRES_PASSWORD=polls_django_password
      - POSTGRES_DB=polls_django_prod

volumes:
  postgres_data:
